name: Set Project Priority from Issue Label

on:
  issues:
    types: [opened, labeled]

jobs:
  set-priority:
    runs-on: ubuntu-latest

    steps:
      - name: Set priority in GitHub Project
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name.toLowerCase());

            const priorityMap = {
              'low': 'Low',
              'medium': 'Medium',
              'high': 'High',
              'critical': 'Critical'
            };

            const matchedLabel = Object.keys(priorityMap).find(label => labels.includes(label));
            if (!matchedLabel) {
              console.log("No priority label found. Skipping.");
              return;
            }

            const priorityValue = priorityMap[matchedLabel];
            const issueNodeId = issue.node_id;

            const projects = await github.graphql(`
              query($issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    projectItems(first: 10) {
                      nodes {
                        id
                        project {
                          id
                          title
                        }
                      }
                    }
                  }
                }
              }
            `, { issueId: issueNodeId });

            const targetProjectName = "3" 
            const projectItem = projects.node.projectItems.nodes.find(item =>
              item.project && item.project.title === targetProjectName
            );

            if (!projectItem) {
              console.log(Issue is not part of the project '${targetProjectName}'.);
              return;
            }

            const projectId = projectItem.project.id;
            const itemId = projectItem.id;

            const fieldsQuery = await github.graphql(`
              query($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2SingleSelectField {
                          id
                          name
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, { projectId });

            const priorityField = fieldsQuery.node.fields.nodes.find(f => f.name === "Priority");
            if (!priorityField) {
              console.log("Priority field not found in project.");
              return;
            }

            const option = priorityField.options.find(opt => opt.name === priorityValue);
            if (!option) {
              console.log(Priority option '${priorityValue}' not found.);
              return;
            }

            await github.graphql(`
              mutation($itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: "${projectId}",
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: {
                    singleSelectOptionId: $optionId
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              itemId,
              fieldId: priorityField.id,
              optionId: option.id
            });
