

name: Set Issue Priority

on:
  issues:
    types: [opened, labeled]

jobs:
  set-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 'low' label and set priority
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name.toLowerCase());

            if (labels.includes('low')) {
              const issue_number = issue.number;
              const repo = context.repo.repo;
              const owner = context.repo.owner;

              await github.rest.issues.update({
                owner,
                repo,
                issue_number,
                labels: [...labels, 'priority: low']
              });

              console.log(Priority set to low for issue #${issue_number});
            } else {
              console.log('No low label found, skipping priority update.');
            }
