name: Add to GitHub Project

on:
 issues:
   types: [opened]

jobs:
 add-to-project:
   runs-on: ubuntu-latest
   steps:
     - name: Add issue to project
       uses: skeet70/default-project-board-action@v1
       with:
         project-url: https://github.com/orgs/jaganpaz/DemoFoodOrdering
         github-token: ${{ secrets.SRIS_TOKEN }}
